project:
  type: website

website:
  title: "Jake Day"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
  twitter-card: true

format:
  html:
    theme: yeti
    css: styles.css

