---
title: "Jake Day"
about:
  template: solana
  links:
    - icon: twitter
      text: twitter
      href: https://twitter.com/Jake_Day4
    - icon: github
      text: Github
      href: https://github.com/jakeday4
    - icon: ai-google-scholar
      text: Google Scholar
      href: https://scholar.google.com/citations?user=R0-2KvsAAAAJ&hl=en
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/jakeday4/
    - icon: fa-envelope 
      text: Email
      href: mailto:jakeday4@gmail.com---
---

I am an associate professor of criminology at the [University of North Carolina Wilmington](https://uncw.edu/soccrm/). My current research and teaching focuses primarily on 1) criminological theory and 2) replication and reproducibility within the social sciences, with a specific focus on criminology. In the past, I have done work focused on social capital, segregation, and race inequality in labor markets, particularly within the context of [college sports](https://workinprogress.oowsection.org/2016/03/09/racial-segregation-and-job-promotion-among-coaches-in-american-college-football/), as well as [criminal and juvenile justice policy](https://journals.sagepub.com/doi/full/10.1177/0022427814538033). Although I still have some [recent](https://journals.sagepub.com/doi/full/10.1177/0049124119826158) and ongoing research related to labor markets and inequality, it has become less central to my research and teaching over the past few years.

## Education

North Carolina State University \| Raleigh, NC \| PhD in Sociology \| 2012

North Carolina State University \| Raleigh, NC \| M.S. in Sociology \| 2007

Oregon State University \| Corvallis, OR \| B.S. in Sociology \| 2003

## Academic Experience

University of North Carolina Wilmington \| Associate Professor \| August 2020 - present

University of North Carolina Wilmington \| Assistant Professor \| August 2014 - July 2020

Appalachian State University \| Assistant Professor \| August 2012 - July 2014
